server {
    listen 80;
    listen [::]:80;
    server_name foodie.example.com;
    location /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 301 https://foodie.example.com$request_uri; }
}
